### PR TITLE
chore: create Java quickstart description

### PR DESCRIPTION
**Pull request by aliandersonsn**
Search Nurture's recommendation for Java description

## Summary

A concise description of the changes being introduced.
If this is a new Observability Pack, please provide a description of its use cases and a list of the Pack's components.

### Screenshots

Images of any visual changes, such as a dashboard.

### CODE REVIEW

**Comment by polfliet** [comment]
@bradleycamacho I added that APM snippet but would love your review

**Comment by polfliet** [comment]
@bradleycamacho looks like adding the APM snippet exceeds the max description length...

**Comment by aswanson-nr** [comment]
The repository has been renamed to `newrelic/newrelic-quickstarts`. Github will handle routing your remotes to this new url, but we recommend that you update your remote as soon as possible.
**NOTE**: As part of this change, we have moved all the quickstarts from the `/packs` directory to the `/quickstarts` directory. To bring your pull request up to date, please pull in the latest commits from the `main` branch.

Use the following command to set your new remote:
```bash
git remote set-url origin https://github.com/newrelic/newrelic-quickstarts.git
```

Or with an SSH origin
```bash
git remote set-url origin git@github.com:newrelic/newrelic-quickstarts.git
```

**Comment by aswanson-nr** [comment]
The repository has been renamed to `newrelic/newrelic-quickstarts`. Github will handle routing your remotes to this new url, but we recommend that you update your remote as soon as possible.
**NOTE**: As part of this change, we have moved all the quickstarts from the `/packs` directory to the `/quickstarts` directory. To bring your pull request up to date, please pull in the latest commits from the `main` branch.

Use the following command to set your new remote:
```bash
git remote set-url origin https://github.com/newrelic/newrelic-quickstarts.git
```

Or with an SSH origin
```bash
git remote set-url origin git@github.com:newrelic/newrelic-quickstarts.git
```

**Review by bradleycamacho — APPROVED** [review]
I've swept the content, provided a copy edits for brevity, and trimmed it down to fit in the character count. This is ready to go from my end.

**Comment by polfliet** [comment]
Closing, these changes were merged as part of https://github.com/newrelic/newrelic-quickstarts/pull/357

**Pull request closed without merging**
