### PR TITLE
LambdaTest: added new page for HyperExecute widgets

### PR DESCRIPTION
**Pull request by saksham-gg**
# Summary

Adding a new page containing widgets related to HyperExecute testing platform of LambdaTest.

### CODE REVIEW

**Comment by saksham-gg** [comment]
Hi @seemantk, can you please review this PR?

**Review by jcountsNR — APPROVED** [review]
LGTM

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Comment by saksham-gg** [comment]
Thanks for merging @sjyothi54 . However, I still can't see the new page that I've added- 'LambdaTest - HyperExecute Overview' in the LambdaTest Dashboard. Is there anything that I'm missing here?

**Comment by sjyothi54** [comment]
> Thanks for merging @sjyothi54 . However, I still can't see the new page that I've added- 'LambdaTest - HyperExecute Overview' in the LambdaTest Dashboard. Is there anything that I'm missing here?

Hey @saksham-gg Whatever PR's merge this week will go live on Thursday, as the team deploys changes every Thursday.

**Comment by saksham-gg** [comment]
Got it, thanks @sjyothi54 !

**Pull request merged**
