### PR TITLE
Updating Quickstart Name

### PR DESCRIPTION
**Pull request by NetlifyMatt**
There will be multiple Netlify-branded Quickstarts for different use cases, so we think the names for each should be unique and purpose-driven. Updating this one from simply `Netlify` to `Netlify Builds`.

# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

There will be multiple Netlify-branded Quickstarts for different use cases, so we think the names for each should be unique and purpose-driven. Updating this one from simply `Netlify` to `Netlify Builds`.

### CODE REVIEW

**Comment by jpvajda** [comment]
@NetlifyMatt thanks for the contribution! Would you mind singing our CLA above so we can accept this PR? You can click the button in the message above from the CLA assistant.

**Comment by NetlifyMatt** [comment]
> @NetlifyMatt thanks for the contribution! Would you mind singing our CLA above so we can accept this PR? You can click the button in the message above from the CLA assistant.

All set!

**Review by jpvajda — CHANGES_REQUESTED** [review]

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
unrelated to this PR, this quickstart is violating or image count check, I'll need to look into this further

```
Error: Each component should contain no more than 6 screenshots

Please check the following directories:
{
  folder: '/home/runner/work/newrelic-quickstarts/newrelic-quickstarts/quickstarts/netlify',
  dashboardCount: 1,
  imageCount: 8,
  maxImages: 6
}
```

**Comment by jpvajda** [comment]
I fixed the image problem in this PR https://github.com/newrelic/newrelic-quickstarts/pull/932

**Pull request merged**
