### PR TITLE
LambdaTest: dashboard query fix

### PR DESCRIPTION
**Pull request by saksham-gg**
# Summary

This PR is to make a correction in the queries of the newly added `LambdaTest - HyperExecute Overview` dashboard.

### CODE REVIEW

**Comment by saksham-gg** [comment]
@sjyothi54 there's a small fix required in the newly added dashboards. Can you please review this PR? Also please let me know when can this be deployed. Thanks!

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Comment by sjyothi54** [comment]
> @sjyothi54 there's a small fix required in the newly added dashboards. Can you please review this PR? Also please let me know when can this be deployed. Thanks!

hey @saksham-gg, I am merging PR now you can expect it to be live by Thursday

**Comment by saksham-gg** [comment]
Thanks for merging @sjyothi54. By any chance is it possible to get this live before Thursday? Some NewRelic<>LambdaTest users are waiting for this feature.

**Comment by sjyothi54** [comment]
> Thanks for merging @sjyothi54. By any chance is it possible to get this live before Thursday? Some NewRelic<>LambdaTest users are waiting for this feature.

The deployment will be handled by the Jumpstart team. If you have any concerns or urgent issues, please raise them in the #help-jumpstart channel.

**Pull request merged**
