### PR TITLE
chore/deprecate network quickstarts

### PR DESCRIPTION
**Pull request by thezackm**
# Summary

  * remove `network-flow-devices` quickstart; flow UI is natively in product now
  * remove `network-ktranslate-health` quickstart; container health UI is natively in product now

relevant docs links:
[Set up network flow data monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring/)
[ktranslate Docker container health monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/ktranslate-container-health)

### CODE REVIEW

**Comment by aswanson-nr** [comment]
Tossing a do not merge label on while we sync on this deletion

**Comment by aswanson-nr** [comment]
Not stale

**Comment by seemantk** [comment]
Sorry, this is still on my TODO list

**Comment by seemantk** [comment]
The migration from Gatsby to CMS is underway, so we will take care of this once that is complete

**Comment by seemantk** [comment]
Still waiting for the Drupal migration so that we can do this one from that
end

**Comment by aswanson-nr** [comment]
Keep alive please

**Comment by seemantk** [comment]
keepalive

**Comment by seemantk** [comment]
We'll proceed with this, and plan to redirect these pages to the relevant docs pages instead, as suggested by @thezackm:

- [network flows](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring/)
- [container health](https://docs.newrelic.com/docs/network-performance-monitoring/advanced/ktranslate-container-health/)

**Pull request closed without merging**
