### PR TITLE
feat(pack): Added AWS Route 53 quickstart

### PR DESCRIPTION
**Pull request by EmilHammarstrand**
# Summary

Added new AWS Route 53 quickstart. 

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

aws-route-53

### CODE REVIEW

**Review by aswanson-nr — COMMENTED** [review]
Hey @EmilHammarstrand, this dashboard looks good, but there isn't an associated quickstart config or change. As it stands now, nothing in this PR will get published. Is that your intent or would you like to add the quickstart part?

Also, we try to shoot for dashboard screenshots that show them in action, could you possibly grab a screenshot when the dashboard has data flowing in?

**Comment by EmilHammarstrand** [comment]
@aswanson-nr I connected the config file with the dashboard now. 

We don't really use Route53 at our company so can't populate any data..

I saw this quickstart was missing so added some metrics from this dashboard to make a quickstart of it; https://onenr.io/0Bj3B18v6RX

Unsure if it is working as it should, do you know anyone who is using Route53 that could test it?

Thanks and have a great weekend 🏖️

**Comment by aswanson-nr** [comment]
Hey @EmilHammarstrand! Let me ask around and see if I can find someone to test this out for us.

**Comment by aswanson-nr** [comment]
Hey @EmilHammarstrand! We were able to get this tested on our end and we're not seeing any data in the dashboard. I'm going to touch base with some people on my end to get some help putting this together!

**Comment by EmilHammarstrand** [comment]
Hey @aswanson-nr !

Okey, sounds great. 👍 

Is it fine if we can mark this quickstart as "done" then?

So that my company can invoice for this quickstart this month, and not wait until next month? :)

**Comment by polfliet** [comment]
Hey @EmilHammarstrand, we would need a dashboard with real data to validate it's working before we can accept it. Can you create a quick test environment for it?

**Pull request closed without merging**
