### PR TITLE
feat: Glassbox quickstart

### PR DESCRIPTION
**Pull request by jcountsNR**
# Summary

Adding a new Glassbox quickstart. Note: will update an integration guide at a later time.

## Pre merge checklist

- [ x] Did you check you NRQL syntax? - Does it work?
- [ x] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [x ] Did you include an InstallPlan and Documentation reference?
- [ x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

### CODE REVIEW

**Comment by jcountsNR** [comment]
@jpvajda , I can't figure out why this keeps failing the schema compliance. It's fairly straighforward I thought.

**Comment by LizBaker** [comment]
hihi @jcountsNR, we're thinking the linkedEntityGuids fields in the dashboard json (both files) need to have a value of `null`, not `[null]` and our validation didn't handle that well. devex is working on producing a better error message but in the meantime if you grab the latest from main and run the sanitize dashboard script it should fix it up for you

**Comment by jcountsNR** [comment]
@LizBaker great thanks! looks that works now. a few quick notes I'll add for this one, 1. the error was pointing me to the config file not the dashboard, 2. I used the sanitize script so I'm surprised that it did not catch this

**Review by jpvajda — APPROVED** [review]

**Comment by jpvajda** [comment]
@jcountsNR  we put[ in a fix](https://github.com/newrelic/newrelic-quickstarts/pull/861) for this case, so I believe the sanitize script should catch this now. Thanks for working through this with us!

**Pull request merged**
