### PR TITLE
Feat: Updates to DB integration

### PR DESCRIPTION
**Pull request by jcountsNR**
# Summary

The databricks integration has been updated, and this changes the quickstart to match the changes.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?
- [ ] Are you trying to create standalone alerts? Standalone alerts are deprecated. They should only be included in quickstarts.

### CODE REVIEW

**Review by sjyothi54 — COMMENTED** [review]
@jcountsNR Could you please explain why you have named dashboard as spark, datasource as databricks and quickstart as databricks spark. The quickstart name should be same throughout all of these.

**Comment by jcountsNR** [comment]
Hi @sjyothi54 , There may end up being more dashboards later, but this one is particular to spark data that we’re getting from databricks. I guess all of them could be databricks spark and it would be accurate.

**Review by sjyothi54 — COMMENTED** [review]
@jcountsNR Thanks for the clarification. The PR looks good, but could you please remove the changes made to install/third-party/databricks? The install sections are deprecated and thus not required.
Reference link: https://github.com/newrelic/newrelic-quickstarts/blob/release/CONTRIBUTING.md#install-plans-deprecated

**Comment by jcountsNR** [comment]
@sjyothi54 , I reverted the changes, but it's still showing as if it's been edited even though it's an exact match.

**Comment by sjyothi54** [comment]
> @sjyothi54 , I reverted the changes, but it's still showing as if it's been edited even though it's an exact match.

@jcountsNR That's fine; an extra space got added, that's why it's showing in the edited files.

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Pull request merged**
