### PR TITLE
Updates and refinements Delphix for standardization 

### PR DESCRIPTION
**Pull request by nick-mathison**
# Summary
 
Update all Delphix titles and descriptions to better align to value proposition and solution offering.
Updated logos.

Dashboard and alert contents are untouched.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Are all documentation links publically accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [x] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [ ] Did you check that your alerts actually work?  -> Nothing's changed

### CODE REVIEW

**Comment by nick-mathison** [comment]
Question for the code reviewers:
image

1) Why isn't my icon appearing in the top center? It's within the pixel limit, so I'm not sure what's wrong. 
2) How do I update the stock picture on the right size in the tablet/monitor pic?

**Comment by nick-mathison** [comment]
Hi, commenting to keep this PR open. We'll update this page in the next week. 

@seemantk, I need some quick assistance on the above questions. Thanks!

**Comment by seemantk** [comment]
> Hi, commenting to keep this PR open. We'll update this page in the next week.
> 
> @seemantk, I need some quick assistance on the above questions. Thanks!

Happy Friday @nick-mathison let me look into this and I'll get back to you in a few hours

**Comment by nick-mathison** [comment]
Hi @seemantk I am still in need of your assistance. Thanks!

**Comment by nick-mathison** [comment]
Requested Screenshot
delphix-vdb-dashboard

**Comment by nick-mathison** [comment]
Requested Dashboard Screenshot 
delphix-dashboard

**Comment by nick-mathison** [comment]
Hi, 

I'm ready to go through the review process. 

I resolved question 2 from above (it was due to image size), however, question 1 remains a mystery to me. Direction is appreciated. Thanks!

**Review by aswanson-nr — APPROVED** [review]
Hey @nick-mathison! Sorry for the delay on this review.
Regarding your first question, that's an ongoing issue with the preview, you can expect your icon to show up properly when live!

**Comment by nick-mathison** [comment]
Thanks everyone!

**Pull request merged**
