### PR TITLE
feat: Vantage tile

### PR DESCRIPTION
**Pull request by jcountsNR**
# Summary

Simple Vantage quickstart, pointing out the integration there with Vantage. They are a cloud cost company that monitors cloud spend across all cloud providers (AWS, GCP, Azure, and other cloud tools including NR.)

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### CODE REVIEW

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Review by RamanaReddy8801 — COMMENTED** [review]
Hi @jcountsNR, I have noticed that this integration doesn't have a datasource. Please update the datasource for this integration. below is the sample template link to use for creating a datasource: https://github.com/newrelic/newrelic-quickstarts/blob/main/_template/data-sources/example-data-source/config.yml.

**Comment by jcountsNR** [comment]
Hi @RamanaReddy8801 , there is no datasource here since this is a cloud pricing tool. They export the data from nerdgraph and use it to view their cloud spend alongside aws/azure/etc.

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Pull request merged**
