### PR TITLE
Video updates

### PR DESCRIPTION
**Pull request by cjmccarthy**
# Summary

Updating dashboards for web quickstarts

videojs

### CODE REVIEW

**Review by jpvajda — APPROVED** [review]
This looks great, and thanks for the contribution!

**Review by jpvajda — CHANGES_REQUESTED** [review]
One suggestion: @cjmccarthy could you ensure the dashboard images follow our naming conventions defined here?

> File name should be quickstart_name01, quickstart_name02, etc

https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboard-screenshots

**Comment by cjmccarthy** [comment]
Good catch! Changed the names to conform with the spec

**Comment by jpvajda** [comment]
@cjmccarthy thank you! 🙏

**Review by jpvajda — APPROVED** [review]

**Pull request merged**
