### PR TITLE
Update various otel quickstart links to new locations

### PR DESCRIPTION
**Pull request by jack-berg**
We've recently rework the opentelemetry docs. All the examples demonstrating infrastructure monitoring with the collector have been consolidated into a single page, with links out to directories in [newrelic-opentelemetry-examples](https://github.com/newrelic/newrelic-opentelemetry-examples) where the source code lives. Also, the directory structure has changed and all of the opentelemetry docs have moved locations, with the root now [https://docs.newrelic.com/docs/opentelemetry/opentelemetry-introduction/](https://docs.newrelic.com/docs/opentelemetry/opentelemetry-introduction/).

We recently had some customer feedback that one of the quickstart links for an opentelemetry integration was broken. https://github.com/newrelic/docs-website/pull/17975 fixes the redirects on the docs site so that users with old links land in useful places. This PR here fixes the links at the source.

### CODE REVIEW

**Comment by zstix** [comment]
Hey @jack-berg, would you mind signing our CLA? Once that's done, we can review and merge this work. Thanks!

**Comment by jack-berg** [comment]
All set @zstix

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Pull request merged**
