### PR TITLE
Changing query for http connections

### PR DESCRIPTION
**Pull request by MahithaB**
# Summary

Changing NRQL query for HTTP connections widget in jfrog-artifactory dashboard for jfrog-platform quickstart

### CODE REVIEW

**Review by MichelLosier — COMMENTED** [review]
Looks good just need the CLA signed!

**Comment by MahithaB** [comment]
@MichelLosier I've signed the CLA and got a thank you message as response. However, the status is not reflected. Can you please help me out? Thanks!

**Comment by MichelLosier** [comment]
In the CLA message above - could you try the link in the message:

> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-quickstarts?pullRequest=2150) it.

Sounds like that might help here

**Comment by MahithaB** [comment]
@MichelLosier the link helps and I can finally see the CLA signed being reflected in the status. Thank you!

**Review by MichelLosier — DISMISSED** [review]

**Comment by MahithaB** [comment]
@MichelLosier could you give me the timeline for freeze? Thanks!

**Comment by MahithaB** [comment]
@MichelLosier @seemantk can you please review the PR. Thanks!

**Review by jcountsNR — DISMISSED** [review]

**Review by sarahkitten — APPROVED** [review]

**Pull request merged**
