### PR TITLE
feat: Update network-flow-devices data source

### PR DESCRIPTION
**Pull request by mickeyryan42**
https://new-relic.atlassian.net/browse/NR-172764

Updating the data source to point to `network-syslog` as per the first A/C.

### CODE REVIEW

**Review by brammerl — APPROVED** [review]
Waiting for Alec to confirm that the PR failure is okay before merging

**Comment by aswanson-nr** [comment]
Yep, that's just a helper job that updates an unused project board!

**Review by brammerl — CHANGES_REQUESTED** [review]

**Review by brammerl — APPROVED** [review]
I misunderstood the ticket AC and am approving once again bc we do want to remove the tile itself!

**Review by d3caf — DISMISSED** [review]

**Review by brammerl — APPROVED** [review]

**Comment by aswanson-nr** [comment]
Not stale

**Review by d3caf — APPROVED** [review]

**Review by brammerl — APPROVED** [review]

**Pull request merged**
