### PR TITLE
feat(zebrium): Added a Quickstart for zebrium

### PR DESCRIPTION
**Pull request by rodbagg**
# Summary

A concise description of the changes being introduced. If you are submitting a PR for a
new quickstart please review the pre merge checklist section to validate this PR is ready for review.

## Pre merge checklist

- [ ] Did you check you NRQL syntax? - Does it work?
- [ ] Did you check your dashboard image quality? -  Do they look good?
- [ ] Did you check that your alerts actually work?
- [ ] Did you include an InstallPlan and Documentation reference?
- [ ] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [ ] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

### CODE REVIEW

**Comment by jcountsNR** [comment]
Hi @rodbagg , thanks for the submission! This looks great. I just have a few asks on my end for this one.

1. Delete the alerts if you don't plan to create new alerts
2. Remove the second dashboard
3. Rename the dashboard image name to zebrium_rcaas_dashboard01.png
4. Remove line 32 on the config.yml. The data source link lives on it's on, so there is no reason to call it out in the quickstart
5. change the 'new relic partner' keyword to 'newrelic partner'

**Comment by rodbagg** [comment]
Address @jcountsNR feedback:
Delete the alerts if you don't plan to create new alerts
Remove the second dashboard
Rename the dashboard image name to zebrium_rcaas_dashboard01.png
Remove line 32 on the config.yml. The data source link lives on it's on, so there is no reason to call it out in the quickstart
change the 'new relic partner' keyword to 'newrelic partner'

**Review by aswanson-nr — COMMENTED** [review]
Looks good! I'll just get that field name changed and merge

**Comment by aswanson-nr** [comment]
Hey @rodbagg, we just need you to sign the Contributor License Agreement before we can merge. It doesn't look like the email used for the commits is attached to a github account, so you may need to go add it to your account before it will associate them.

**Comment by rodbagg** [comment]
@aswanson-nr Both rodbagg@yahoo.com and rod@zebrium.com are now associated to this github account. I went through the signing process again. Hope all is ok now.

**Review by josephgregoryii — APPROVED** [review]

**Pull request merged**
