### PR TITLE
Kubernetes infra samples

### PR DESCRIPTION
**Pull request by maxlemieux**
# Summary

Updated following widgets to use infra samples in their queries. This is because certain metric > infra shims aren't working for all encountered account data.

- Kubernetes tab > # of K8s Objects
- Kubernetes tab > Namespaces Per Cluster
- Kubernetes tab > Node Resource Consumption
- Kubernetes tab > Active Pods by Deployment
- Kubernetes tab > Pod Count by Node

- Kubernetes Clusters and Nodes tab > Clusters
- Kubernetes Clusters and Nodes tab > Nodes
- Kubernetes Clusters and Nodes tab > Nodes count widgets, serverless Nodes, Running Pods, % Pods Running

- Kubernetes Pod Status tab > Overall Pod Status
- Kubernetes Pod Status tab > Pod status by cluster
- Kubernetes Pod Status tab > Latest Pending Pods
- Kubernetes Pod Status tab > Latest Failed Pods

- Kubernetes Utilization > CPU % by Namespace

Unrelated fix also included: 
- Kubernetes Cluster Events tab > Cluster Events (remove hard coded cluster name, added column headers)

## Pre merge checklist

- [X] Did you check you NRQL syntax? - Does it work?
Yes, I reproduced the shim problem with each query before updating it to use infra samples, then verified the new query worked on the same account where the shim problem exists.

- [X] Did you include an InstallPlan and Documentation reference?
Existing

- [X] Are all documentation links publically accessible?
No new ones, I checked existing links and all are public

- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
N/A

- [X] Did you check your descriptive content for spelling and grammar errors?
Yes, checked that the new column headers in Kubernetes Cluster Events > 'Cluster Events' widget appear correct

### Dashboards 

- [X] Does the PR contain a screenshot for each of your dashboards?
N/A, existing screenshots should be applicable

- [X] Do your screenshots show data?
N/A

- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?
Assuming N/A, not a new dashboard, no structural changes to JSON only NRQL changes

### Alerts

- [X] Did you check that your alerts actually work?
N/A

### CODE REVIEW

**Comment by brammerl** [comment]
Hello, We are no longer accepting install plans as a part of the quickstart schema. We are instead moving to use data sources. You can either refer to an [already existing data source](https://github.com/newrelic/newrelic-quickstarts/tree/main/data-sources) in this repository or[ make your own](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources-1) community data source. 

If this applies to your PR, please make the proper update to your quickstart's config to reference only data sources.

**Comment by maxlemieux** [comment]
> Hello, We are no longer accepting install plans as a part of the quickstart schema. We are instead moving to use data sources. You can either refer to an [already existing data source](https://github.com/newrelic/newrelic-quickstarts/tree/main/data-sources) in this repository or[ make your own](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources-1) community data source.
> 
> If this applies to your PR, please make the proper update to your quickstart's config to reference only data sources.

Thank you, I will review the draft and make necessary changes.

**Comment by maxlemieux** [comment]
Keeping alive for another stale cycle while checking if this is still needed.

**Comment by seemantk** [comment]
hi @maxlemieux thank you. Please let me know if and how I can support you

**Pull request closed without merging**
