### PR TITLE
stage status fix

### PR DESCRIPTION
**Pull request by saksham-gg**
# Summary

A small fix to match existing field in logs.

### CODE REVIEW

**Comment by saksham-gg** [comment]
Hey @sjyothi54 can you please merge this? Also, where can I find the #help-jumpstart channel as you mentioned?

**Review by sjyothi54 — APPROVED** [review]
looks good

**Review by pkudikyala — APPROVED** [review]
LGTM!

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Pull request merged**
