### PR TITLE
feat(elixir): add elixir agent quickstart

### PR DESCRIPTION
**Pull request by abrunner94**
# Summary

Introduce a quickstart and install plan for the [New Relic open source Elixir agent](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/elixir/elixir-open-source-agent/). 

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots

Attach images of any visual changes, such as a dashboard here.

### CODE REVIEW

**Comment by abrunner94** [comment]
Also curious to know if Elixir is purposely avoided in the quickstarts and install plan, considering (I remember) customers asking for it. :)

Whatever the case may be, drop in some feedback!

**Comment by kidk** [comment]
Amazing ❤️  thanks @abrunner94

**Review by polfliet — APPROVED** [review]
Thanks for your contribution @abrunner94! This is great.
We did a migration from newrelic.com/integrations and I guess the Elixir agent was missing there.

Do you also have a dashboard/alert(s)? That would make the quickstart even more awesome. But we can already merge this in

**Comment by jbeveland27** [comment]
> I've been seeing something like id: 87d.... in some, if not all of the quickstarts. Is this something that gets added?

@abrunner94 Yep this gets added automatically by the [release workflow](https://github.com/newrelic/newrelic-quickstarts/blob/main/.github/workflows/release.yml#L13) after we merge, so you don't need to worry about adding an `id` 😄

**Pull request merged**
