### PR TITLE
LambdaTest: modified queries according to modified data

### PR DESCRIPTION
**Pull request by saksham-gg**
# Summary

Made some changes to the dashboard queries according to the changes made in data.

### CODE REVIEW

**Comment by saksham-gg** [comment]
@sjyothi54 can you please review and merge this PR. Also I hope this will get deployed tomorrow i.e. Thursday.

**Comment by saksham-gg** [comment]
Hi @sjyothi54 @RamanaReddy8801, can you please merge this PR today so that it gets deployed today itself? Thanks!

**Comment by saksham-gg** [comment]
Hi @RamanaReddy8801 can you please check this PR?

**Review by sjyothi54 — APPROVED** [review]
LGTM

**Review by RamanaReddy8801 — APPROVED** [review]
LGTM

**Pull request merged**
