### PR TITLE
Update Mongodb prometheus screenshot

### PR DESCRIPTION
**Pull request by jessieziyuantang**
Update Mongodb prometheus screenshot

# Summary

A concise description of the changes being introduced. Please review the pre-merge checklist section to validate this pull request is ready for review and merge. **If it is not ready, please mark the pull request as a draft.**

_The owners of this repo are not experts in the subject matter of the quickstarts. We review for the quickstart to be functional and for security risks. If you are seeking feedback on the content of the quickstart, please seek out a subject matter expert. If you are not an internal NR contributor, we can do our best to connect you with a content reviewer._

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [x] Did you check that your alerts actually work?

### CODE REVIEW

**Comment by brammerl** [comment]
Please sign our CLA before we review this! https://github.com/newrelic/newrelic-quickstarts/pull/1696#issuecomment-1470846554

**Review by zstix — APPROVED** [review]

**Comment by zstix** [comment]
Hey @jessieziyuantang would you mind signing the CLA. Without that, we're unable to merge this PR

**Comment by jessieziyuantang** [comment]
> Hey @jessieziyuantang would you mind signing the CLA. Without that, we're unable to merge this PR

Thanks for remind me, done

**Review by seemantk — APPROVED** [review]
looks great, the new screenshots are much better

**Comment by seemantk** [comment]
@jessieziyuantang thank you.  Can you please add a screenshot of your CLA sign because the automated check doesn't detect it

**Comment by zstix** [comment]
It looks like this still needs to be signed @jessieziyuantang, here's where you need to go to handle that:
Screenshot 2023-03-30 at 09 53 29

**Pull request merged**
