### PR TITLE
Remove MSSQL Query Plans Quickstart

### PR DESCRIPTION
**Pull request by jbeveland27**
# Summary

This is to remove the [Microsoft SQL Server Query Plans quickstart](https://newrelic.com/instant-observability/nri-mssql-query-plans) and all related resources (dashboard, data source, installPlan).

We've taken steps to archive the NRI behind this Quickstart (https://github.com/newrelic-experimental/nri-mssql-experimental) as it was an experimental integration that has outlived its purpose. This PR is to tie up the loose ends and finish removing it from our public I/O catalog.

### CODE REVIEW

**Comment by csalvador-nr** [comment]
I've opened a PR (#2165) to update this quickstart instead of removing it. I think it can still provide value used alongside with custom SQL queries.

**Comment by csalvador-nr** [comment]
Keeping it open.

**Comment by rahulbasu-nr** [comment]
Let's not remove the quickstart. Please close this PR.

**Comment by jbeveland27** [comment]
Closing in favor of #2165

**Pull request closed without merging**
