### PR TITLE
feat(pack) Added totally new pack, fastAPI. Python web framework for …

### PR DESCRIPTION
**Pull request by EmilHammarstrand**
…building RESTful APIs.

# Summary

New pack, fastAPI. A python web framework for building fast and modern RESTful APIs.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### CODE REVIEW

**Review by polfliet — DISMISSED** [review]
You have to remove the id line from the config file, it will be autogenerated and then the error will disappear

**Review by aswanson-nr — DISMISSED** [review]
Overall looks great! Just some small comments around the dashboard json

**Comment by jpvajda** [comment]
@EmilHammarstrand 👋 could you resolve the failed check? 

```
Error: quickstarts/python/fastapi/dashboards/fastAPI.json
	 '/pages/1' must have required property 'name'
	 '/pages/1' must have required property 'description'
	 '/pages/1' must have required property 'widgets'
	 '/pages/1' must match a schema in anyOf
```

**Review by jpvajda — CHANGES_REQUESTED** [review]
see comments on failed check

**Comment by EmilHammarstrand** [comment]
@jpvajda All checks has passed now!

**Review by jpvajda — APPROVED** [review]

**Pull request merged**
