### PR TITLE
ArgoCD QuickStart #940

### PR DESCRIPTION
**Pull request by shawnj**
# Summary

New Quickstart for ArgoCD : https://github.com/newrelic/newrelic-quickstarts/issues/940

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### Screenshots
argocd_screen_001
argocd_screen_002
argocd_screen_003
argocd_screen_004

### CODE REVIEW

**Review by jpvajda — APPROVED** [review]
This looks great, thanks for the contribution, @shawnj ! Not sure if you want anyone else with SME knowledge to review this before it's merged, but from my POV this looks good to go.

**Comment by shawnj** [comment]
@jpvajda Let me have someone on my side take a look.

**Comment by shawnj** [comment]
@jpvajda Also, this is a V1.  I want to add an alert and verify it works as expected.

**Comment by shawnj** [comment]
@jpvajda Looks good on our side.  What are the next steps for merging?

**Comment by jpvajda** [comment]
@shawnj I just merged it in. 🚀

**Pull request merged**
