### PR TITLE
ArgoCD Quickstart update

### PR DESCRIPTION
**Pull request by bpschmitt**
# Summary

- Adding dashboard template variables
- Widget fixes and updates
- Modified install plans to only include Prometheus Server or Prometheus Agent

- [X] Did you check you NRQL syntax? - Does it work?
- [X] Did you include an InstallPlan and Documentation reference?
- [X] Are all documentation links publicly accessible?
- [X] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)? 
- [X] Did you check your descriptive content for spelling and grammar errors?

### Dashboards 

- [X] Does the PR contain a screenshot for each of your dashboards?
- [X] Do your screenshots show data?
- [X] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- Alerts coming soon...

### CODE REVIEW

**Review by seemantk — APPROVED** [review]
This looks good, thank you Brad!

**Review by aswanson-nr — COMMENTED** [review]
Hey @bpschmitt, this looks good! I noticed that the alert policies are not attached to the quickstart, did you want to add that?

**Comment by brammerl** [comment]
Hello, We are no longer accepting install plans as a part of the quickstart schema. We are instead moving to use data sources. You can either refer to an [already existing data source](https://github.com/newrelic/newrelic-quickstarts/tree/main/data-sources) in this repository or[ make your own](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#data-sources-1) community data source. 

If this applies to your PR, please make the proper update to your quickstart's config to reference only data sources.

**Comment by brammerl** [comment]
This has been excluded from the mandatory data source migration so it can be merged with install plans if it has any.

**Review by aswanson-nr — APPROVED** [review]
Looks good!

**Pull request merged**
