### PR TITLE
feat(pack): Updated Kinesis Firehose

### PR DESCRIPTION
**Pull request by EmilHammarstrand**
# Summary

Updated the dashboard and added an alert.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you check your dashboard image quality? -  Do they look good?
- [x] Did you check that your alerts actually work?
- [x] Did you include an InstallPlan and Documentation reference?
- [x] Did you check your descriptive content for voice, tone, spelling and grammar errors?
- [x] Did you attach images of your dashboards to the PR so we can see them working?

### CODE REVIEW

**Comment by EmilHammarstrand** [comment]
I'm not sure why I got an error indside quickstarts/releaseiq

**Comment by jpvajda** [comment]
@EmilHammarstrand 👋  I see 2 failures here. We have a new service that is doing back end checks for PRs now so I believe that may be what you are seeing. I'll bring in one of our Engineers to help troubleshoot this PR. 

https://github.com/newrelic/newrelic-quickstarts/runs/5300104868?check_suite_focus=true


```
Error: quickstarts/releaseiq/dashboard/riq-dashboard.json
	 must have required property 'title'
	 must have required property 'level'
	 must have required property 'authors'
	 must have required property 'logo'
```


https://github.com/newrelic/newrelic-quickstarts/runs/5300104930?check_suite_focus=true

 Error: Each component should contain no more than 6 screenshots

```
  folder: '/home/runner/work/newrelic-quickstarts/newrelic-quickstarts/quickstarts/releaseiq',
  dashboardCount: 0,
  imageCount: 1,
  maxImages: 0
```

**Comment by jpvajda** [comment]
@EmilHammarstrand I worked with @nr-kkenney on what is occuring here, and this is actually relating to another quickstart that is from #845 that snuck through and is now throwing some errors. 

We are going to look into what is occurring on these failures, as there may be a bug with our checks.

**Comment by jpvajda** [comment]
https://github.com/newrelic/newrelic-quickstarts/issues/857

**Review by jpvajda — APPROVED** [review]

**Pull request merged**
