### PR TITLE
feat: New quickstart kong

### PR DESCRIPTION
**Pull request by jcountsNR**
# Summary

Request from @louisleungk for a quickstart. uses Kong logs.

## Pre merge checklist

- [x] Did you check you NRQL syntax? - Does it work?
- [x] Did you include a Data source and Documentation reference?
- [x] Are all documentation links publicly accessible?
- [x] Did you check your descriptive content for [voice and tone](https://docs.newrelic.com/docs/style-guide/writing-strategies/voice-strategies-docs-sound-new-relic/)?
- [x] Did you check your descriptive content for spelling and grammar errors?
- [x] Did you review your content with a subject matter expert? (e.g. a Browser agent quickstart is reviewed with a member of the Browser Agent team)

### Dashboards

- [x] Does the PR contain a screenshot for each of your dashboards?
- [x] Do your screenshots show data?
- [x] Has the [sanitization script](https://github.com/newrelic/newrelic-quickstarts/blob/main/CONTRIBUTING.md#dashboards) been run on each dashboard?

### Alerts

- [x] Did you check that your alerts actually work?
- [x] Are you trying to create standalone alerts? Standalone alerts are deprecated. They should only be included in quickstarts.

### CODE REVIEW

**Review by sjyothi54 — COMMENTED** [review]
@jcountsNR, I have noticed that this integration doesn't have a datasource. Is this quickstart intended for use without a datasource?

**Comment by jcountsNR** [comment]
@sjyothi54 I added a datasource here. Since it is a logging integration, there isn't a custom dashboard alongside it, just the ootb logs viewer.

**Review by sjyothi54 — APPROVED** [review]
Looks good

**Review by pkudikyala — APPROVED** [review]
LGTM!

**Pull request merged**
